version: "3"

services:
  algorithm:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      # 设置Host 为 localhost 进行域名访问
      - traefik.http.routers.algorithm.rule=Host(`algorithm.merlin218.top`)
      # 开启HTTPS
      - traefik.http.routers.algorithm.tls=true
      - traefik.http.routers.algorithm.tls.certresolver=le

networks:
  default:
    external:
      name: traefik_default
